Adding capability to report sub second records on JtsDocument.toJSON
slaxor505/json-timeseries-py pull request #1
Opened 2024-03-22 02:41 UTC by redin

Adding capability to report sub second records on JtsDocument.toJSON.
The old implementation would only report one record if more than one are under the same second.
Changing the key on sort we allowed the lib to report on the microsecond interval
Added a test as well.

2024-03-24 10:05 UTC, slaxor505 requested changes
Hi Redin,

Thanks a lot for contribution. I've reviewed the change and really appreciate that you pointed to this flow. I researched that a bit and I suggest to use 

r.timestamp.timestamp()

instead 

r.timestamp.isoformat(timespec='microseconds')

Because the latter produces a string while the former produces float of Epoc timestamp with milliseconds. I believe the float is more suitable as sorting key than string. If you can modify as proposed and re-submit, it'd be great!

2024-03-27 02:05 UTC, redin commented
Thank you for the review.
I was aiming for microsecond records when I proposed the first change.
I think we can live with millisecond.
Change done.

2024-04-03 11:44 UTC, slaxor505 commented
Hi Redin,

Thanks for the change. I was checking your test and I think there is a room for improvement as the sub_second test does not really test that sequence of ts records is in correct sequence. If you don't mind I'd suggest that you add them in some odd order and then in your test verify that they are correctly sorted. If it is too much effort then leave it and I will add it later when I have a bit of spare time.

Thank you.

2024-04-05 21:13 UTC, redin commented
I'll do it this weekend.

2024-04-07 21:04 UTC, redin commented
Added test to verify sorting of records on miliseconds.

2024-04-09 11:43 UTC, slaxor505 approved these changes
Thank you for your contribution.

2024-04-09 11:43 UTC, merged